name: target_photo_dash
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_riverpod: ^2.4.0
  hooks_riverpod: ^2.4.0
  camera: ^0.9.4+5
  image_picker: ^1.0.4
  image: ^4.1.3
  firebase_core: ^2.15.1
  google_mlkit_image_labeling: ^0.9.0
  google_mlkit_commons: ^0.5.0


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.3
  mockito: ^5.4.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/pic_target_photo_dash_home.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/pic_target_photo_dash_home.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/pic_target_photo_dash_home.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/pic_target_photo_dash_home.png"

flutter:
  uses-material-design: true
  assets:
   - assets/pic_target_photo_dash_home.png
   - assets/labels.txt
   - assets/target_labels.txt
